comment:
  layout: header, changes, diff
coverage:
  ignore:
    - "tests/.*"
    - "setup.py"
    - "xform/check.py"
    - "SuperCoolFast/SuperCoolFast.py"
  status:
    project: yes
    patch: yes
    changes: no
